#!/bin/sh
coffee -o build/ -b -c src && \
coffee -j build/pl0-coffee.js -b -c \
	src/tag \
	src/token \
	src/lexer && \

./node_modules/.bin/mocha \
	--reporter spec \
	--compilers coffee:coffee-script \
	--require should \
	--require spec/node_test_runner.js \
	--require build/pl0-coffee.js \
	--slow 75 \
	--growl \
	./spec/*.coffee
