#!/usr/bin/env python

import os

from fsevents import Observer, Stream

def callback(subpath, mask):
  os.system('./run_test')

os.system('./run_test')
stream = Stream(callback, './spec', './src')
observer = Observer()
observer.start()
observer.schedule(stream)
