# define PL/0 language symbols
Compiler.TAG = [
  'nul', # 0
  'identifier', # 1
  'number', # 2
  '+',  # 3
  '-',  # 4
  '*',  # 5
  '/',  # 6
  '=',  # 7
  '<>', # 8
  '<',  # 9
  '<=', # 10
  '>',  # 11
  '>=', # 12
  '(',  # 13
  ')',  # 14
  ',',  # 15
  ';',  # 16
  '.',  # 17
  ':=', # 18
  'odd',        # 19
  'begin',      # 20
  'end',        # 21
  'if',         # 22
  'then',       # 23
  'while',      # 24
  'do',         # 25
  'call',       # 26
  'const',      # 27
  'var',        # 28
  'procedure',  # 29
  'read',       # 30
  'write',      # 31
]
